### ISSUE TITLE
Make library more testable

### ISSUE THREAD

**Issue by vidarkongsli** [vip30/WebPush-NetCore#1]
Hi,

Would you accept a pull request for making the library more test-friendly? I think it would be benficial to have an overloaded constructor for the `WebPushClient` that takes an `HttpMessageInvoker` to inject an alternative object that sends off the request to the remote service. That way, I would be easier to add automated testing to any project using the library.

--Vidar

**Comment by vip30** [comment]
Just feel free to make a pull request :)

**Comment by vidarkongsli** [comment]
Great, but there's one test failing (`TestSendFCMMessage`). I would like to have all tests passing before I start so that I can feel confident that I don't break anything. Do you have any idea about why the test is failing?

**Comment by vip30** [comment]
I will take a look later as I am on vacation right now.

Maybe next week can reply to you.
Thanks for your comment :)

**Comment by vip30** [comment]
After checking, original repo is already supported .netCore so I will archive this repo now.
